Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
extra : source : 164d68b15de7d55e8d63b7733d1404134665a2b4