Rails3 compabitility: remove shoulda associations assertions
On Rails 3.1 with shoulda 2.11:
<pre>
/xxxx/test/unit/project_test.rb:63:in `<class:ProjectTest>': undefined method `validate_presence_of' for ProjectTest:Class (NoMethodError)

from /xxxx/test/unit/project_test.rb:16:in `<top (required)>'
</pre>

git-svn-id: svn+ssh://rubyforge.org/var/svn/redmine/trunk@9088 e93f8b46-1217-0410-a6f0-8f06a7374b81